// async-modal-vue/src/App.vue
<template>
  <div id="app">
    <div>
      <el-button @click="openModal">open modal</el-button>
    </div>
    <div style="margin-top: 20px">
      {{result}}
    </div>
    <HelloWorld ref="asyncModal"/>
  </div>
</template>

<script>
import HelloWorld from './components/AsyncModal.vue'

export default {
  name: 'app',
  data() {
    return {
      result: ''
    }
  },
  components: {
    HelloWorld
  },
  methods: {
    async openModal() {
      if (this.$refs.asyncModal) {
        try {
          const x = await this.$refs.asyncModal.open();
          console.log(x)
          this.result = `get result: ${x}`
        } catch(e) {
          console.log(e)
          this.result = `catch error: ${e}`;
        }
      }
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  position: absolute;
  width: 100%;
  top: 40%;
}
</style>

// async-modal-react/src/App.js
import React from 'react';
import './App.css';
import { Button } from 'antd';
import AsyncModal from './components/async_modal_hoc';

class App extends React.Component {

  state = {
    result: ''
  }
  handleOpenModal = async () => {
    if (this.refs.asyncModal) {
      try {
        const result = await this.refs.asyncModal.open();
        console.log(result)
        this.setState({ result: `get result ${result}` })
      } catch(e) {
        console.log(e)
        this.setState({ result: `catch error ${e}` })
      }
    }
  }

  render() {
    return (
      <div className="App">
        <Button
          onClick={this.handleOpenModal}
        >
          Open Modal
        </Button>
        <div style={{ marginTop: 20 }}>
          {
            this.state.result
          }
        </div>
        <AsyncModal ref="asyncModal"></AsyncModal>
      </div>
    );
  }
}

export default App;
